### PR TITLE
Minimal error printing

### PR DESCRIPTION
**Pull request by timsaucer**
This is a pretty small change (branched off from my comment-rendering branch, so probably best to merge that one first). Basically it makes the debug comments far less verbose. Only developers really need the stack traces.

### CODE REVIEW

**Comment by marinier** [comment]
I'm not sure the stack traces should be suppressed at this point. This project still has issues that regular users run into, and the stack traces are often the only clue they can give us as to what's happening. I would at least want to make it a parameter.

What is the purpose in limiting the debug output anyway? It's in the console, which most users won't even look at unless something is going wrong, in which case they can send it to us. Or is there some other issue (e.g., performance is suffering because of the volume of output)?

**Comment by timsaucer** [comment]
After talking to Bob, I'll update this to have a setting in the configuration for debug mode. In that config, it will dump the full stack trace.

**Comment by adeschamps** [comment]
I reproduced this locally. You also need to bump the version of `@types/node` - `13.5.0` will work (and maybe earlier). You can either merge #234 and then rebase this PR, or bump it manually and dependabot will close that PR automatically.

**Comment by adeschamps** [comment]
This is failing for the same reason as #236 - merge #234 first, and then it should build.

**Comment by marinier** [comment]
Build is passing again. I confirmed that the file not found exception trace is suppressed (it just prints an error message without the trace). However, I appear to get a similar file not found exception trace from `Analysis` right after (Analysis.java:298), so maybe it needs to be suppressed there, too?

Also, I don't see a setting to enable a debug mode. This isn't necessarily a deal breaker, but if @timsaucer still intends to add it we can wait on merging.

**Comment by marinier** [comment]
We decided to merge it as-is.

**Pull request merged**
