### PR TITLE
Comment rendering

### PR DESCRIPTION
**Pull request by timsaucer**
Can you please take a look at the tests? I'm unfamiliar with what they're failing on, but I suspect it's just checking a binary that has changed.

In this update, I've done two things: Bumped the level of the vscode-languageclient and (more importantly) enabled the configuration parameters from the user settings to actually be used by the soar language server when using vs code. While I was debugging it, I found I needed to bump up the language client version to get it to work properly. I added one new setting for rendering the comments verbatim (markdown) or plain text (default so behavior should be unchanged for existing users).

### CODE REVIEW

**Comment by marinier** [comment]
This is the error from here: https://travis-ci.com/soartech/soar-language-server/builds/146261389

```
npm ERR! code EINTEGRITY

npm ERR! sha512-7jrS/9WnV0ruqPamN1nE7qCxn0phkH5LjSgSp9h6qoJGoeAKzwKz/PF6M+iGA/aklx4GLZg1prddhEPQtuXI1Q== integrity checksum failed when using sha512: wanted sha512-7jrS/9WnV0ruqPamN1nE7qCxn0phkH5LjSgSp9h6qoJGoeAKzwKz/PF6M+iGA/aklx4GLZg1prddhEPQtuXI1Q== but got sha512-Tcp0VoOaa0YzxL4nEfK9tsmcy76Eo8jNLvFQZwh2c8oMm02luL8uGYPLQNAiZ3XGgegfcwiQFZMqbW7DNV0vxA==. (51480 bytes)
```

**Comment by adeschamps** [comment]
It looks like the minimum engine version of the VSCode extension is too old. It's currently at `1.32`.

https://github.com/soartech/soar-language-server/blob/9a9f95e3fc1f325197cdb942f0a5664a78340414/integrations/vscode/package.json#L13-L15

I believe most installations of VSCode are configured to automatically update, so it's _probably_ safe to raise the minimum version to whatever you need to get it to build. I'm on `1.41`. This should also make #235 pass as well.

```bash
$ code --version                      
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64
```

**Comment by adeschamps** [comment]
I reproduced this locally. You also need to bump the version of `@types/node` - `13.5.0` will work (and maybe earlier). You can either merge #234 and then rebase this PR, or bump it manually and dependabot will close that PR automatically.

**Comment by adeschamps** [comment]
Well, this is surprising. When I checkout this commit, if I run `npm install` _once_, then I get a diff with +5/-5 changed lines in `package-lock.json`. If I run `npm run compile` at that point, it fails like it does in travis. However, if I make _no other changes_, and simply run `npm install` again, then I now have a diff with +33/-25 changed lines in `package-lock.json` and `npm run compile` will succeed.

I would have expected the dependency resolver to settle on the final answer the first time. I'm not sure what's going on.

In any case, the solution is to commit the changes to `package-lock.json`

**Comment by adeschamps** [comment]
Interesting.... if I delete `package-lock.json` _before_ running `npm install`, then it picks the right dependency set the first time.

**Comment by adeschamps** [comment]
I went ahead and updated the lock file. If this works, I'd suggest rebasing #237 on here.

**Comment by timsaucer** [comment]
Thank you, Anthony.

**Comment by timsaucer** [comment]
@sirnuke Can you test this push and make sure it's working as expected? Also, is everyone in agreement with approach of making this a user setting?

**Comment by marinier** [comment]
I'm in agreement. I actually wonder if the default should be the current behavior or the markdown. I envision a future where everyone just uses markdown format for comments, and it becomes a forcing function if the default behavior is markdown. However, it could also be confusing if people think comments are suddenly all messed up. Either way, at least for now when things are transitioning, having the option to change it is great.

**Comment by timsaucer** [comment]
I just discovered this still isn't working as expected. It looks like right now we're sending either raw text (verbatim as it's listed in the code) or markdown with the 4 spaces to make it show up as code comments. We probably want 3 options: raw text (for any environments that don't render markdown), markdown as code (the current behavior), and markdown. I'm assigning it to myself because I'll probably work on it this weekend.

**Comment by timsaucer** [comment]
I realized nobody actually uses the "markdown as a code block" option, so just made a quick renaming to be more explicit about what's now going to happen. Either raw text or markdown without the prefixed 4 spaces. Default (for now) is raw text.

**Comment by marinier** [comment]
This is passing tests now -- can I merge it, or is there more work to be done?

**Comment by timsaucer** [comment]
I was hoping someone else would give it a try before merging, but yes I think it's ready now.

**Comment by marinier** [comment]
I'll give it a try when I get a chance. Certainly, the aim would be to have all pull requests merged before the next release.

**Comment by marinier** [comment]
FYI, I was trying to test this and it refused to build for me (`npm run compile` failed claiming that ```
```
Namespace '"vscode"' has no exported member 'SymbolTag'.
```
In 5 different places. But deleting `package-lock.json` and regenerating it with `npm install` seems to have fixed the issue (and updated a bunch of the contents of `package-lock.json`). Not sure why I had to do that.

I'm testing locally now, and assuming it's all good, I'll push the change, and then assuming travis passes, I'll merge this PR.

**Pull request merged**
